services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet_tx
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
