spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:wallet_tx}
    username: ${POSTGRES_USER:wallet}
    password: ${POSTGRES_PASSWORD:wallet}
    driver-class-name: org.postgresql.Driver
